### ISSUE TITLE
Number of containers in execution node

### ISSUE THREAD

**Issue by rajat503** [prasadtalasila/JavaAutolab#14]
In each execution node should there be multiple docker containers each taking a maximum of one job or only one container taking multiple jobs?
I'm more inclined towards multiple containers in one node due to the following reasons despite the overhead of running containers:

- It gives complete isolation to each job.

- A malicious job can only affect a container and other containers can still take submissions. 

- The system doesn't delay the response of marks until all jobs at the node are finished giving faster performance.

**Comment by prasadtalasila** [comment]
Docker containers themselves don't provide as much of isolation. Since the containers are quick, the containers do solve the job queuing problem.

It is better to launch one evaluation job in a dedicated container.
