### ISSUE TITLE
Installation Package

### ISSUE THREAD

**Issue by prasadtalasila** [prasadtalasila/JavaAutolab#16]
We really need an installation script for the software. The following steps may help with creation of installation script.

1. Where ever files need to be changed, create sample files and copy these sample files over the existing files in the docker container.
2. Assume default cache directory for installation. Or, user can specify this cache directory through an installation config file.
3. If IP addresses need to be specified, let the user specify them in a default config file for installation.

We need to go with the standard open source flow of configure-make-make install cycle. Please see relevant documentation to create this - [1](https://robots.thoughtbot.com/the-magic-behind-configure-make-make-install), [2](http://stackoverflow.com/questions/10999549/how-do-i-create-a-configure-script), [3](http://stackoverflow.com/questions/10961439/why-always-configure-make-make-install-as-3-seperate-steps?rq=1).

**Comment by prasadtalasila** [comment]
Typical *NIX installation scripts require configuration, compilation copying to target directories and cleaning up of temporary files. We do not need compilation. 

I found a [tutorial](https://nodejs.org/en/docs/guides/nodejs-docker-webapp/) on nodejs site which does packaging of node.js applications for Docker. Here is another [tutorial](https://docs.docker.com/v1.10/engine/examples/nodejs_web_app/) on the Docker site. 

Seems a suitable way forward for us.

**Comment by rajat503** [comment]
We are already doing what is mentioned in the tutorial in the container building step. I followed this tutorial while writing the Dockerfiles. The configuration of the execution node has to be done after starting the container because of the parameters involved. Other configs can be done before building the build.

**Comment by prasadtalasila** [comment]
The existing [Docker files](https://github.com/prasadtalasila/JavaAutolab/blob/master/main_server/Dockerfile) are not taking complete advantage of RUN, WORKDIR, COPY commands. We can use these commands to completely automate the installation process. 

For example, see the [load balancer](https://github.com/prasadtalasila/JavaAutolab/wiki/Two-Machines#deploying-load-balancer-on-machine-1) installation instructions. Steps 5 to 7 of the load balancer installation can be completed using COPY and WORKDIR commands. Ofcourse, appropriate json settings file must be generated apriori using a shell script or a node.js program or any configuration program.

I can forsee one way to make this possible. Have a text file for configuration. The install shell script or node.js program reads the central configuration file and generates all the required json configuration files. We can have the central configuration file in json format. Given the existing knowledge of node.js ecosystem in the team, it may be better to just have a web page with form to be filled by the administrator installing the application. The node.js application generates the required configuration files and spreads them into correct directories. After that, a shell script can bind together all the SSL key generation steps and the microservices start up steps.

The only place where a manual intervention is required is database manipulation. For this, we can use DB restore to restore default users and passwords. Or we can use GitLab API to accomplish automation of this step as well.
