### ISSUE TITLE
GitLab API

### ISSUE THREAD

**Issue by rajat503** [prasadtalasila/JavaAutolab#20]
From the email discussion:

Two kinds of scenarios.
1) administrator creating / managing users (once a semester, may be)
2) lab author performing the following weekly tasks
    a) creating new repository for lab statement and solutions
    b) creating a skeleton repository in all the students accounts

There are many GitLab API wrapper clients available. For smooth operation, it is better to choose node.js-based package or Java-based package. For the first task, it may be better to choose Node.js based package. Administrator can perform the user creation task.

For the second task, we need to use Java wrapper available. We may need to write another wrapper code that takes in a config file with the following information.
1) authentication   2) user-list in a separate file  3) local weekly repository with solutions  4) skeleton repository

A lab author provides the config file which will be used to create an authoritative solution in lab authors namespace, create skeleton repository in all the student namespaces.

Having this wrapper in Java would make it easy for the lab authors to finish their weekly work. If the given Java wrapper does not work, it may be prudent to write a simple Java package containing the required set of classes that would make the necessary API calls.

**Comment by prasadtalasila** [comment]
Low priority. Postponed to future work.
