### ISSUE TITLE
Quality Control for Project

### ISSUE THREAD

**Issue by prasadtalasila** [prasadtalasila/JavaAutolab#21]
A good linter and debugger can help take minor bugs out of the way in time. There is a list of linters and debuggers on [linters](https://github.com/mcandre/linters) repo.

[JSHint](http://jshint.com/docs/cli/), [JSLint](http://jslint.com/function.html) and [JSLint Errors](http://jslinterrors.com/) seem like good additions to your tool chain for quality control in our project.

**Comment by rajat503** [comment]
I used JSHint on our JS files and the errors it pointed out were just a matter of notation in JavaScript - the language allows the syntax we are using. Also, the kind of bugs we run into are usually related to missing out on test cases.
