### ISSUE TITLE
Timezones in containers

### ISSUE THREAD

**Issue by prasadtalasila** [prasadtalasila/JavaAutolab#25]
The containers must use a configurable timezones. Ideally this would be based on the system time or as set in the DockerFile

Some useful references in this direction:
[timezone in DockerFile](http://serverfault.com/questions/683605/docker-container-time-timezone-will-not-reflect-changes)    
[Sync with base OS](http://stackoverflow.com/questions/24551592/how-to-make-sure-dockers-time-syncs-with-that-of-the-host)

**Comment by tejas-sangol** [comment]
Binding the file "/etc/localtime" to that of the container when the container is run solves the issue. 

There is no need of any change in the Dockerfile or the existing images in production.

The docker containers have to be restarted with the below command 

(The part in bold is the addition to fix the issue).

Example ->   sudo docker run -dit --net=host --name main_server -v /etc/localtime:/etc/localtime:ro main_server
