### ISSUE TITLE
webapp UI improvements

### ISSUE THREAD

**Issue by prasadtalasila** [prasadtalasila/JavaAutolab#26]
The following improvements would be helpful.

1. **Time specification for the lab.**     
Instead of specifying one single date, it is better to specify date on both start and end times in the following format.    
Start Time: 15:00, 9-8-2016    
End Time: 17:00, 9-8-2016    
2. **Update on submit page**    
If the lab is not active, we can show a message at the top    
"_Lab is no longer active. The result of this evaluation shall not be added to the score card._"

**Comment by rajat503** [comment]
Implemented.
The inactive lab messsage is shown just below the score after the evaluation. Submit page might not always have the updated status (like in yesterday's lab). The score page receives the status of the time when the request hits the main server and whether the scoreboard update happened or not.
