### ISSUE TITLE
time and commit hash columns on score board

### ISSUE THREAD

**Issue by prasadtalasila** [prasadtalasila/JavaAutolab#29]
There seems to be quite a bit of confusion on the scores shown on the score board and the corresponding commits. Would having two extra columns, time and commit hash/label help resolve this mental block?

What would be the difficulty of adding these two to the scoreboard?

**Comment by rajat503** [comment]
The scores on the scoreboard are the highest obtained across all commits. Students are expected to code until all test cases pass without worrying about the score. Meaningful commit messages will help more than putting a commit hash and time on the scoreboard. 

About the difficulty of adding - time should not be hard, we already have that value in the database. Adding commit hash in cases no commit hash was entered while submitting might require an extra step in the execution node code.

**Comment by prasadtalasila** [comment]
Then let's just add the time to the scoreboard. That may help people figure out their last evaluation time.

**Comment by prasadtalasila** [comment]
time has been added and commit hash feature request postponed to later
