### ISSUE TITLE
Changes on execute.sh

### ISSUE THREAD

**Issue by ashubits** [prasadtalasila/JavaAutolab#30]
1. add class path `export CLASSPATH="lib/*:."`
2. Suppress -Xlint warning

Suggested fix:
`cat log.txt >> ../log.txt`
  `errors=$(wc -l log.txt | awk '{print $1}')`  
  `errors2=$(grep -v "^Note:" log.txt | wc -l | awk '{print $1}')`  
  `if [ $errors2 -eq 0 ];`  
  `then`  

3. Copy student libraries in working directory after moving author solution
    `cp -r ./student_solution/lib working_dir/`

**Comment by prasadtalasila** [comment]
Taken care of by the new execution script. See commit d77da27
