### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by prasadtalasila** [prasadtalasila/JavaAutolab#43]
Installation on Azure cloud VM fails. see [attachment](https://www.dropbox.com/s/snknt55ghrmf2qo/autolab-azure-installation-error.zip?dl=1) for detailed log.

**Comment by gnarula** [comment]
gitlab_hostname variable in inventory must be updated to Public IP of Machine 1 in both loadbalancer and executionnodes groups

**Comment by prasadtalasila** [comment]
I tried with the following inventory file
```
[mysql]
localhost ansible_connection=local ansible_python_interpreter=/usr/bin/python2 sqldata=/opt/sqldata mysql_root_pass=root

[gitlab]
104.214.66.65 ansible_connection=local ansible_python_interpreter=/usr/bin/python2 gitlab_password=12345678

[loadbalancer]
localhost ansible_connection=local ansible_python_interpreter=/usr/bin/python2 submissions_dir=../load_balancer/submissions gitlab_hostname=104.214.66.65 gitlab_password=12345678

[mainserver]
localhost ansible_connection=local ansible_python_interpreter=/usr/bin/python2

[executionnodes]
10.0.0.5 ansible_connection=ssh ansible_user=<user> ansible_password=<password> ansible_python_interpreter=/usr/bin/python2 gitlab_hostname=104.214.66.65 gitlab_password=12345678 port=8082
```

Even with the new configuration, the installation error is same as before.

**Comment by prasadtalasila** [comment]
Installation is a partial success with the following inventory file.

[mysql]
localhost ansible_connection=local ansible_python_interpreter=/usr/bin/python2 sqldata=/opt/sqldata mysql_root_pass=root

[gitlab]
13.85.66.218 ansible_connection=local ansible_python_interpreter=/usr/bin/python2 gitlab_password=12345678

[loadbalancer]
localhost ansible_connection=local ansible_python_interpreter=/usr/bin/python2 submissions_dir=../load_balancer/submissions gitlab_hostname=10.0.0.4 gitlab_password=12345678

[mainserver]
localhost ansible_connection=local ansible_python_interpreter=/usr/bin/python2

[executionnodes]
10.0.0.5 ansible_connection=ssh ansible_user=<user> ansible_password=<passwd> ansible_python_interpreter=/usr/bin/python2 gitlab_hostname=10.0.0.4 gitlab_password=12345678 port=8082

The [wiki page](https://github.com/prasadtalasila/JavaAutolab/wiki/v0.2-beta-Deployment-on-Two-Machines) has been updated with the appropriate instructions.

Post installation, the container of main_server is continuously restarting. I think we saw this problem earlier, and knew the solution. The corresponding corrections need to go into the dev repository.

**Comment by prasadtalasila** [comment]
The commit 6ae6c81 solves the above installation error.
