### ISSUE TITLE
Making Docker Containers

### ISSUE THREAD

**Issue by rajat503** [prasadtalasila/JavaAutolab#5]
- Every execution node should be a separate container.

- Load balancer, database and the main server should be in one machine.

- See the tradeoff for GitLab

**Comment by rajat503** [comment]
Docker has images for mysql and GitLab separately and they can be deployed straight away as services like we have in our development environment. Should efforts be made to run all services (main server, load balancer, GitLab, mysql) in a single container or have separate containers for each? The recommended deployment links are given below:

- MySQL: https://hub.docker.com/_/mysql/

- GitLab: http://docs.gitlab.com/omnibus/docker/

Having different containers allows us to move a particular microservice to any other system in production if required.

**Comment by prasadtalasila** [comment]
Nope. The MySQL and GitLab containers can be deployed on the same machine. No need to combine them as such and lose the community support in the process.

**Comment by rajat503** [comment]
The docker procedure is complete and it seems to work.
