### ISSUE TITLE
Selecting Branch and Commit for evaluation in Git

### ISSUE THREAD

**Issue by rajat503** [prasadtalasila/JavaAutolab#9]
Users should be able to specify branch name for which the latest commit will be evaluated.
Users can also specify commit id to evaluate a particular commit.

**Comment by rajat503** [comment]
`git checkout <sha1>` brings the directory to the commit having hash `<sha1>` and we can do the evaluation by using the files in this state. This takes care of the branch as well.
We'll need users to enter the commit hash every time they want to submit (be it last commit on `master`). Does it sound like the increasing the complexity of the process of submission which already has become a little complex because of GitLab?

**Comment by prasadtalasila** [comment]
Yes...sha1 entry does make it a little more complicated. Why not let a blank sha1 entry to mean the last commit?

**Comment by rajat503** [comment]
Implemented. Leaving it blank takes the latest commit on `master` branch. For anything else, just the commit hash is required.
